### ISSUE TITLE
真机无法运行

### ISSUE THREAD

**Issue by GeekBud** [wkl007/flutter_trip#1]
flutter build apk打包发送至安卓真机后无法运行，安装完成后点击没有任何反应

**Comment by wkl007** [comment]
我这没有问题呀

**Comment by WANGNlMA** [comment]
你好，我也同样遇到了这样的问题，但是下载二维码中的包是没问题的，您课程中有没有解决的方法啊？没有买您的课程，对这点我不太了解？

**Comment by wkl007** [comment]
我不是CrazyCodeBoy老师，我也是看了他的视频的。你那先试试模拟器能不能打开，我用的flutter是dev版本的。
